# Expiry values are in seconds
# 1 day = 86400
# Add a new test in the following way
# eg
# ---
# ExampleTest: 86400
---
Example: 86400
# 91 days and 6 hours (~ 3 months)
AccountBankHols: 7884000
ExploreMenuAbTestable: 86400
