# Expiry values are in seconds
# 1 day = 86400
# Add a new test in the following way
# eg
# ---
# ExampleTest: 86400
---
Example: 86400
RelatedLinksAATest: 2419200  # 4 weeks
RelatedLinksABTest1: 2419200 # 4 weeks
RelatedLinksABTest2: 2419200 # 4 weeks
RelatedLinksABTest3: 2419200 # 4 weeks
RelatedLinksABTest4: 43200 # 12 hours
ViewDrivingLicence: 259200
