# Please leave the 'Example' test config in place and active.
#
# You should create <test name>_percentages.yaml to configure
# bucket allocations. See example_percentages.yaml for format.
---
Example: true
RelatedLinksAATest: false
RelatedLinksABTest1: false
RelatedLinksABTest2: false
RelatedLinksABTest3: false
RelatedLinksABTest4: false
ViewDrivingLicence: false
FinderAnswerABTest: true
