# These are the base paths of the pages we consider to be
# pages related to starting a business.
# Setting a value to false will cause it to not be included.
---
/correct-your-business-rates: false
/send-rent-lease-details: false
/find-government-property: false
/contact-your-local-council-about-business-rates: false
/find-an-energy-assessor: false
/send-vat-return: false
/use-construction-industry-scheme-online: false
/file-your-company-accounts-and-tax-return: false
/pay-tax-direct-debit: false
/pay-tax-debit-credit-card: false
/marginal-relief-calculator: false
/barriers-trading-investing-abroad: false
/check-eori-number: false
/check-duties-customs-exporting: false
/get-rules-tariffs-trade-with-uk: false
/trade-tariff: false
/licence-finder: false
/file-your-confirmation-statement-with-companies-house: false
/file-changes-to-a-company-with-companies-house: false
/file-your-company-annual-accounts: false
/contracts-finder: false
/find-tender: false
/data-protection-register-notify-ico-personal-data: false
/check-when-businesses-pay-invoices: false
/digital-marketplace: false
/planning-permission-england-wales: false
/introduction-to-business-rates: false
/calculate-your-business-rates: false
/run-business-from-home: false
/apply-for-business-rate-relief: false
/energy-performance-certificate-commercial-property: false
/workplace-fire-safety-your-responsibilities: false
/workplace-temperatures: false
/renting-business-property-tenant-responsibilities: false
/scaffolding-rules: false
/terminating-a-commercial-property-lease-early: false
/can-i-use-cctv-at-my-commercial-premises: false
/water-and-sewerage-rates-for-businesses: false
/who-is-responsible-for-asbestos-found-in-my-commercial-property: false
/non-domestic-renewable-heat-incentive: false
/appeal-lawful-development-certificate-decision: false
/get-rebate-refund-business-rates: false
/get-your-air-conditioning-system-inspected: false
/register-boat-coastguard-safety-scheme: false
/right-to-contest-answer: false
/renewing-your-commercial-property-lease: false
/pay-vat: false
/pay-corporation-tax: false
/vat-registration: false
/vat-returns: false
/corporation-tax: false
/prepare-file-annual-accounts-for-limited-company: false
/capital-allowances: false
/company-tax-returns: false
/reclaim-vat: false
/tell-hmrc-changed-business-details: false
/corporation-tax-rates: false
/what-you-must-do-as-a-cis-subcontractor: false
/vat-businesses: false
/what-you-must-do-as-a-cis-contractor: false
/tax-buy-shares: false
/work-out-capital-allowances: false
/corporation-tax-accounting-period: false
/first-company-accounts-and-return: false
/vat-registration-thresholds: false
/capital-gains-tax-businesses: false
/dormant-company: false
/tax-compliance-checks: true]
/tax-tribunal: false
/capital-allowances-sell-asset: false
/tax-when-your-company-sells-assets: false
/tax-limited-company-gives-to-charity: false
/pay-construction-industry-scheme-cis-late-filing-penalty: false
/get-refund-interest-corporation-tax: false
/government/collections/venture-capital-schemes-hmrc-manuals: false
/wood-packaging-import-export: false
/take-goods-sell-abroad: false
/taking-goods-out-uk-temporarily: false
/intrastat: false
/research-export-markets: false
/overseas-customers-export-opportunities: false
/eori: false
/goods-sent-from-abroad: false
/vat-on-services-from-abroad: false
/limited-company-formation: false
/strike-off-your-company-from-companies-register: false
/running-a-limited-company: false
/closing-a-limited-company: false
/directors-loans: false
/annual-accounts: false
/search-the-register-of-disqualified-company-directors: false
/audit-exemptions-for-private-limited-companies: false
/change-your-companys-year-end: false
/register-as-an-overseas-company: false
/company-director-disqualification: false
/appeal-a-penalty-for-filing-your-company-accounts-late: false
/make-changes-to-your-limited-company: false
/queens-awards-for-enterprise: false
/object-to-a-limited-company-being-struck-off: false
/set-up-property-management-company: false
/restart-a-non-trading-or-dormant-company: false
/cartels-price-fixing: false
/file-accounts-in-the-uk-as-an-overseas-company: false
/accepting-returns-and-giving-refunds: false
/online-and-distance-selling-for-businesses: false
/trading-hours-for-retailers-the-law: false
/invoicing-and-taking-payment-from-customers: false
/data-protection-your-business: false
/tendering-for-public-sector-contracts: false
/product-labelling-the-law: false
/weights-measures-and-packaging-the-law: false
/marketing-advertising-law: false
/pedlars-certificate: false
/doorstep-selling-regulations: false
/respond-data-protection-request: false
/unfair-terms-in-sales-contracts: false
/entertainment-and-modelling-agencies: false
/uk-registered-deaths: false
/employers-liability-insurance: false
/employment-agencies-and-businesses: false
/growing-your-business: false
/employing-staff: false
/set-up-business: false
