# These are the base paths of the pages we consider to be
# pages related to starting a business.
# Setting a value to false will cause it to not be included.
---
/correct-your-business-rates: true
/send-rent-lease-details: true
/find-government-property: true
/contact-your-local-council-about-business-rates: true
/find-an-energy-assessor: true
/send-vat-return: true
/use-construction-industry-scheme-online: true
/file-your-company-accounts-and-tax-return: true
/pay-tax-direct-debit: true
/pay-tax-debit-credit-card: true
/marginal-relief-calculator: true
/barriers-trading-investing-abroad: true
/check-eori-number: true
/check-duties-customs-exporting: true
/get-rules-tariffs-trade-with-uk: true
/trade-tariff: true
/licence-finder: true
/file-your-confirmation-statement-with-companies-house: true
/file-changes-to-a-company-with-companies-house: true
/file-your-company-annual-accounts: true
/contracts-finder: true
/find-tender: true
/data-protection-register-notify-ico-personal-data: true
/check-when-businesses-pay-invoices: true
/digital-marketplace: true
/planning-permission-england-wales: true
/introduction-to-business-rates: true
/calculate-your-business-rates: true
/run-business-from-home: true
/apply-for-business-rate-relief: true
/energy-performance-certificate-commercial-property: true
/workplace-fire-safety-your-responsibilities: true
/workplace-temperatures: true
/renting-business-property-tenant-responsibilities: true
/scaffolding-rules: true
/terminating-a-commercial-property-lease-early: true
/can-i-use-cctv-at-my-commercial-premises: true
/water-and-sewerage-rates-for-businesses: true
/who-is-responsible-for-asbestos-found-in-my-commercial-property: true
/non-domestic-renewable-heat-incentive: true
/appeal-lawful-development-certificate-decision: true
/get-rebate-refund-business-rates: true
/get-your-air-conditioning-system-inspected: true
/register-boat-coastguard-safety-scheme: true
/right-to-contest-answer: true
/renewing-your-commercial-property-lease: true
/pay-vat: true
/pay-corporation-tax: true
/vat-registration: true
/vat-returns: true
/corporation-tax: true
/prepare-file-annual-accounts-for-limited-company: true
/capital-allowances: true
/company-tax-returns: true
/reclaim-vat: true
/tell-hmrc-changed-business-details: true
/corporation-tax-rates: true
/what-you-must-do-as-a-cis-subcontractor: true
/vat-businesses: true
/what-you-must-do-as-a-cis-contractor: true
/tax-buy-shares: true
/work-out-capital-allowances: true
/corporation-tax-accounting-period: true
/first-company-accounts-and-return: true
/vat-registration-thresholds: true
/capital-gains-tax-businesses: true
/dormant-company: true
/tax-compliance-checks: true]
/tax-tribunal: true
/capital-allowances-sell-asset: true
/tax-when-your-company-sells-assets: true
/tax-limited-company-gives-to-charity: true
/pay-construction-industry-scheme-cis-late-filing-penalty: true
/get-refund-interest-corporation-tax: true
/government/collections/venture-capital-schemes-hmrc-manuals: true
/wood-packaging-import-export: true
/take-goods-sell-abroad: true
/taking-goods-out-uk-temporarily: true
/intrastat: true
/research-export-markets: true
/overseas-customers-export-opportunities: true
/eori: true
/goods-sent-from-abroad: true
/vat-on-services-from-abroad: true
/limited-company-formation: true
/strike-off-your-company-from-companies-register: true
/running-a-limited-company: true
/closing-a-limited-company: true
/directors-loans: true
/annual-accounts: true
/search-the-register-of-disqualified-company-directors: true
/audit-exemptions-for-private-limited-companies: true
/change-your-companys-year-end: true
/register-as-an-overseas-company: true
/company-director-disqualification: true
/appeal-a-penalty-for-filing-your-company-accounts-late: true
/make-changes-to-your-limited-company: true
/queens-awards-for-enterprise: true
/object-to-a-limited-company-being-struck-off: true
/set-up-property-management-company: true
/restart-a-non-trading-or-dormant-company: true
/cartels-price-fixing: true
/file-accounts-in-the-uk-as-an-overseas-company: true
/accepting-returns-and-giving-refunds: true
/online-and-distance-selling-for-businesses: true
/trading-hours-for-retailers-the-law: true
/invoicing-and-taking-payment-from-customers: true
/data-protection-your-business: true
/tendering-for-public-sector-contracts: true
/product-labelling-the-law: true
/weights-measures-and-packaging-the-law: true
/marketing-advertising-law: true
/pedlars-certificate: true
/doorstep-selling-regulations: true
/respond-data-protection-request: true
/unfair-terms-in-sales-contracts: true
/entertainment-and-modelling-agencies: true
/uk-registered-deaths: true
/employers-liability-insurance: true
/employment-agencies-and-businesses: true
/growing-your-business: true
/employing-staff: true
/set-up-business: true
